library(ggplot2)
library(plotly)
library(dplyr)
library(scales)
library(tidyr)
library(tidyverse)
library("mapproj")
library("maps")
library("rbokeh")
library("shiny")

climate_data <- read.csv("https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv")

#Which country has the highest cumulative oil CO2 within the last 50 years?
high_country <- climate_data %>%
  filter(year >= 1970 & year <= 2020) %>%
  group_by(country) %>%
  summarize(amount_gas_co2 = sum(gas_co2_per_capita, na.rm = T)) %>% filter(amount_gas_co2 == max(amount_gas_co2)) %>%
  pull(country)

#Top 5 countries and its iso_code with lowest amount of co2 per capita:

climate_data <- climate_data %>% mutate(location = paste(country,'-', iso_code))

low_country <- climate_data %>% group_by(location) %>% 
  summarize(amount_co2 =sum(co2_per_capita, na.rm = T)) %>% arrange(desc(amount_co2)) %>% slice(1:5) %>% pull(location)


#Location (country abd its iso_code) that is the lowest net exporter (lowest negative trade_co2_share)
lowest_location <- climate_data %>% group_by(location) %>% filter(trade_co2_share < 0) %>% 
  summarize(trade_share = sum(trade_co2_share, na.rm = T)) %>% filter(trade_share == min(trade_share)) %>% 
  pull(location)



#Location (country abd its iso_code) that is the highest net importer (highest positive trade_co2_share)
highest_location <- climate_data %>% group_by(location) %>% filter(trade_co2_share > 0) %>% 
  summarize(trade_share = sum(trade_co2_share, na.rm = T)) %>% filter(trade_share == min(trade_share)) %>% pull(location)


server <- function(input, output) {
  
  #Amount of Oil co2 per capita across country
  output$climatePlot <- renderPlotly({
    climate_data <- climate_data %>% filter(country %in% input$user_category)
    climate_data <- climate_data %>% filter(year >= input$slider2[1]) 
    climate_data <- climate_data %>% filter(year <= input$slider2[2])
    
    #figure(title = "Oil CO2 Per Capita Worldwide") %>% 
    #  ly_lines(year, oil_co2_per_capita, data = climate_data, color = country) %>% 
    #  x_axis(label = "Year") %>% 
    #  y_axis(label = "Oil CO2 Per Capita")

    #output$range <- renderPrint({climate_data <- climate_data %>% filter(input$year_range)})

    my_plot <- ggplot(data = climate_data) +
      geom_line(mapping = aes(x = year, 
                              y = oil_co2_per_capita, 
                              color= country)) +
      labs(title = 'Oil CO2 Per Capita Worldwide', x='Year', y='Oil CO2 Per Capita', color ='Country') 
    
    my_plotly_plot <- ggplotly(my_plot)
    
    return(my_plotly_plot)

  })
  #output$range <- renderPrint({input$year_range})  # filter (year %in% input$year_range)
  
#Compare co2 per capita between US and Vietnam 
  output$co2_comparisonPlot <- renderPlotly({
    compare_data <- climate_data %>%
      filter(year %in% input$user_year ) %>% 
      group_by(year) %>%
      summarize(Vietnam = sum(co2_per_capita, na.rm = T),
                United_States = sum(co2_per_capita, na.rm = T))
    
    trend_data <- pivot_longer(compare_data, 2:3, names_to = "Country", values_to = "total_co2_per_capita")
    
    compare <- ggplot(data = trend_data) +
      geom_col(mapping= aes(x=year, y = total_co2_per_capita, fill = Country), position = "dodge") +
      labs(title = 'Total CO2 per capita Vietnam vs US from 2010 to 2020', x='Year', y='Total CO2 Per Capita') 
    ggplotly(compare)
    
  })
  output$Text1 <- renderText({"- The data set provides details information and data on CO2 emission data around the globe.The data was collected by Our World in Data. The data is collected from multiple sources. CO2 emissions data is sourced from the Global Carbon Project, Greenhouse gas emissions data from the CAIT Climate Data Explorer, Energy from BP Statistical Review of World Energy and World Bank, other sources from United Nationas, Gapminder, Maddison Project Databases, etc. All data is generated by the following steps. First is standardizing names of countries and regions. Next is recalculating carbon emissions to CO2, then calculating per capita figures. All of the per capita figures are calculated from our metric Population, which is included in the complete dataset. These population figures are sourced from Gapminder and the UN World Population Prospects (UNWPP). The data is collected to update people on CO2 emissions (annual, per capita, cumulative and consumption-based), other greenhouse gases, energy mix, and other relevant metrics on an annual basis. Generally, it is an easy dataset to work with. But there are still a lot of null values. This means the comparison between these groups will be affected by the range and how many null values it has. A lot of information lead to a lot of potential analysis so it might be a challenge for me to fully understand, come up with specific columns to work with, and think of potential chart/ maps to work on. So first, I have to clean records where it is null for consistency. I need to pay extra attention when working with these  columns and always ignore NA values. "})
  output$Value <- renderText({
    paste0("- I'm interested in 5 values. The first value is the country has the highest cumulative oil CO2 within the last 50 years, which was ", high_country, ". Next is top 5 location (country name and its isco_code) with lowest amount of co2 per capita: ",low_country[1]," and ",low_country[2]," and ",low_country[3]," and ",low_country[4]," and ",low_country[5],". I'm also interested in finding out the location that is the lowest net exporter (lowest negative trade_co2_share), which was ",lowest_location,".In contrast, I also found the location (country and its iso_code) that is the highest net importer (highest positive trade_co2_share), which was ",highest_location,"") })
    
    output$Text2 <- renderText({"- The purpose of this chart is to compare the amount of OIL CO2 per capita across countries. Users can select multiple countries can compare the amount of OIL CO2 per capita.  The chart is interesting because it also shows a certain preiod of time that there is no data on present (so there is a gap in the line). For example, when the user choose Angola, there is no data till 1950. Another interesting thing about this chart is that users can choose to compare between developed and developing countries. It's a common assumption that developing countries (Vietnam. China...) will have higher Oil CO2 emissions due to its air pollution, but in fact, these countries have quite similar OIL CO2 per campita when comparing to the US or UK. "})
    output$Text3 <- renderText({"- The purpose of this bar chart is comparing the TOTAL CO2 per capita between the US and Vietnam by year. Users can select multiple years (doesn't have to be continuous), and they will get 2 columns in that specific year. The chart is interesting because it compares specifically the total co2 per capita between 2 very different countries. One is the world's most developed country, the US. The other is a developing country which has heavy air pollution, Vietnam. However, when we compare the total co2 per capita between these 2 countries, they have a quite similar pattern throughout the past 100 years."})
    output$Text4 <- renderText({"Prompt: Long-term Health and Well-Being."})
    output$Text5 <- renderText({"- 3 ways that the system influences health and well-being after years of use. - As technology have both direct and indiret effects on people's health and well-being, the first impact of technology on human health is how technology gets personal health information of a person and promote customized personal health care. - Secondly, technology guide people to choose credible health care destination to go to. Just by 1 search on the internet, users can search for how credible a hospital is. how many years it has been operated, its reviews, etc. - Thirdly, technology provides people an opportunity to take care of themselves. Users can search for health care treatments on the internet."})
    
}







